fragment PageParts on Page {
  blocks {
    __typename
    ... on PageBlocksHero {
      title
      subtitle
    }
  }
}

fragment PostParts on Post {
  title
  category
  date
  description
  ogimage
}
