fragment PageParts on Page {
  blocks {
    __typename
    ... on PageBlocksHero {
      title
      subtitle
      image
      position {
        __typename
        text {
          __typename
          colstart
          colend
          rowstart
          rowend
        }
        image {
          __typename
          colstart
          colend
          rowstart
          rowend
        }
      }
    }
    ... on PageBlocksCta {
      title
      subtitle
      button {
        __typename
        label
        href
      }
      position {
        __typename
        text {
          __typename
          colstart
          colend
          rowstart
          rowend
        }
        button {
          __typename
          colstart
          colend
          rowstart
          rowend
        }
      }
    }
    ... on PageBlocksQuote {
      quote
      author
      colstart
      colend
    }
    ... on PageBlocksGallery {
      gallery {
        __typename
        image
        alt
        colstart
        colend
        height
      }
    }
    ... on PageBlocksFact {
      fact {
        __typename
        headline
        subheadline
        colstart
        colend
        height
      }
    }
    ... on PageBlocksLogos {
      headline
      logos {
        __typename
        logo
        alt
        href
      }
    }
    ... on PageBlocksFeatured {
      category
      size
    }
  }
}

fragment PostParts on Post {
  title
  category
  date
  description
  image
}

fragment MapParts on Map {
  date
}
