fragment PageParts on Page {
  blocks {
    __typename
    ... on PageBlocksHero {
      title
      subtitle
      image
      position {
        __typename
        text {
          __typename
          x
          width
          y
          height
        }
        image {
          __typename
          x
          width
          y
          height
        }
      }
    }
    ... on PageBlocksCta {
      title
      subtitle
      button {
        __typename
        label
        href
      }
    }
    ... on PageBlocksQuote {
      quote
      author
      x
      width
    }
    ... on PageBlocksGallery {
      gallery {
        __typename
        image
        alt
        x
        width
        height
      }
    }
    ... on PageBlocksFact {
      fact {
        __typename
        headline
        subheadline
        x
        width
      }
    }
    ... on PageBlocksLogos {
      headline
      logos {
        __typename
        logo
        alt
        href
      }
    }
    ... on PageBlocksCard {
      cards {
        __typename
        title
        body
      }
    }
    ... on PageBlocksFeatured {
      category
      size
    }
  }
}

fragment PostParts on Post {
  title
  category
  date
  description
  image
}

fragment MapParts on Map {
  date
}
